name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        mongodb:
            image: mongo:4.2
            ports:
                - 27017:27017

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install cmake flex bison
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Run tests
      run: pipenv run py.test algernon/
